Uber eats
aggie-coding-club/Broke pull request #44
Opened 2023-04-14 01:13 UTC by AllenSun101

Finished prototype. There's a few things that I might try out in the next few days, but hopefully this works for the most part.

2023-04-14 18:23 UTC, yuqian-cao-19 requested changes
The first time I run it it returned the Chick fil a item for McDonalds as well. The next few times I run the file it gave me a bunch of chromedriver errors. Not sure what's up with that. I'll have Will run the code on his end to see if it's my problem

2023-04-14 23:47 UTC, AllenSun101 commented
Did it fix the bugs?

2023-04-15 23:55 UTC, yuqian-cao-19 approved these changes

2023-04-15 23:59 UTC, yuqian-cao-19 approved these changes

2023-04-15 23:59 UTC, merged